# Generated by Django 4.2.7 on 2024-02-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('signs', '0001_initial'), ('signs', '0002_alter_location_location_id'), ('signs', '0003_alter_location_location_id_alter_location_name'), ('signs', '0004_alter_location_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This name will be displayed on the digital sign.', max_length=100)),
                ('location_id', models.IntegerField(help_text='Location ID must match LibCal ID exactly.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
