# Values for signage prod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: uclalibrary/digital-signage-hours
  tag: v1.0.5
  pullPolicy: Always

nameOverride: ""

fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  
ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: sectigo-acme-clusterissuer
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: 'signage.library.ucla.edu'
      paths:
        - "/"
  tls:
  - secretName: signage-tls
    hosts:
      - signage.library.ucla.edu

django:
  env:
    run_env: "prod"
    debug: "false"
    allowed_hosts:
      - signage.library.ucla.edu
    csrf_trusted_origins:
      - https://signage.library.ucla.edu
    log_level: "INFO"
    libcal_hours_widget: "https://calendar.library.ucla.edu/widget/hours/grid?"
    libcal_events_widget: "https://calendar.library.ucla.edu/api_events.php?m=today&simple=ul_date&cid="
    db_backend: "django.db.backends.postgresql_psycopg2"
    db_name: "signage"
    db_user: "signage"
    db_host: "p-d-postgres.library.ucla.edu"
    db_port: 5432

  externalSecrets:
    enabled: "true"
    annotations: 
      argocd.argoproj.io/sync-wave: "-1"
    env:
      # Application database used by django
      db_password: "/systems/prodrke01/signage/db_password"
      django_secret_key: "/systems/prodrke01/signage/django_secret_key"

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
